language: elixir
dist: bionic

elixir:
  - 1.9.4
  - 1.10.1

otp_release:
  - 21.3.8.13
  - 22.2.6

cache:
  directories:
    - ~/.mix
    - _build/dev

script:
  - mix test
  - mix dialyzer
  - mix credo --strict --all
